$ErrorActionPreference = 'Stop'
$BaseUrl = 'http://127.0.0.1:8080'

function Write-Step($Text) {
  Write-Host "`n[Phase06] $Text" -ForegroundColor Cyan
}

function Invoke-Api($Method, $Url, $Headers = @{}, $Body = $null) {
  $args = @{ Method = $Method; Uri = $Url; Headers = $Headers }
  if ($null -ne $Body) {
    $args.ContentType = 'application/json; charset=utf-8'
    $args.Body = ($Body | ConvertTo-Json -Depth 12)
  }
  Invoke-RestMethod @args
}

function Wait-Until($Name, [ScriptBlock]$Action, [ScriptBlock]$Predicate, $Retries = 20, $DelayMs = 500) {
  for ($i = 0; $i -lt $Retries; $i++) {
    $value = & $Action
    if (& $Predicate $value) { return $value }
    Start-Sleep -Milliseconds $DelayMs
  }
  throw "Timeout while waiting for $Name"
}

try {
  Write-Step 'Checking gateway health...'
  $health = Invoke-RestMethod "$BaseUrl/actuator/health"
  $health | ConvertTo-Json -Depth 10

  Write-Step 'Requesting ADMIN dev token...'
  $tokenResponse = Invoke-Api 'POST' "$BaseUrl/api/auth/dev-token?username=demo&role=ADMIN"
  $tokenResponse | ConvertTo-Json -Depth 8
  $token = $tokenResponse.data.accessToken
  if ([string]::IsNullOrWhiteSpace($token)) { throw 'Token is empty.' }
  $headers = @{ Authorization = "Bearer $token" }
  Write-Host '[Phase06] Token acquired.'

  $bookingDate = (Get-Date).AddDays((Get-Random -Minimum 15 -Maximum 60)).ToString('yyyy-MM-dd')
  $submitBody = @{
    taskName = 'Phase06 outbox consistency inspection'
    orgId = 1
    applicantUserId = 1
    applicantName = 'demo'
    routeTemplateId = 1
    levelId = 1
    bookingDate = $bookingDate
    timeSlotIds = @(3)
    applyReason = 'Phase06 RabbitMQ outbox smoke test'
    description = 'approve -> outbox -> RabbitMQ -> notify -> audit -> idempotent'
  }

  Write-Step "Submitting booking for $bookingDate..."
  $booking = Invoke-Api 'POST' "$BaseUrl/api/bookings" $headers $submitBody
  $booking | ConvertTo-Json -Depth 12
  $bookingId = $booking.data.id
  $bookingNo = $booking.data.bookingNo
  if (-not $bookingId) { throw 'Booking id is empty.' }
  Write-Host "[Phase06] Created booking id=$bookingId no=$bookingNo"

  Write-Step 'Approving booking. This should create an outbox_message in the same business transaction.'
  $approveBody = @{ operatorUserId = 1; operatorName = 'admin'; comment = 'approved by phase06 smoke test' }
  $approved = Invoke-Api 'POST' "$BaseUrl/api/bookings/$bookingId/approve" $headers $approveBody
  $approved | ConvertTo-Json -Depth 12

  Write-Step 'Checking outbox messages for approved booking...'
  $outbox = Wait-Until 'approved outbox message' `
    { Invoke-Api 'GET' "$BaseUrl/api/bookings/outbox?aggregateId=$bookingId&eventType=BOOKING_APPROVED&limit=20" $headers } `
    { param($r) $r.data.Count -ge 1 }
  $outbox | ConvertTo-Json -Depth 12
  $outboxId = $outbox.data[0].id
  $messageKey = $outbox.data[0].messageKey
  Write-Host "[Phase06] Approved outbox id=$outboxId messageKey=$messageKey status=$($outbox.data[0].status)"

  Write-Step 'Forcing outbox dispatch once. Scheduler may already have sent it, so picked=0 is acceptable.'
  $dispatch = Invoke-Api 'POST' "$BaseUrl/api/bookings/outbox/dispatch?limit=20" $headers
  $dispatch | ConvertTo-Json -Depth 8

  Write-Step 'Waiting for notify_record generated by conflict-notify-service consumer...'
  $notify = Wait-Until 'notify record' `
    { Invoke-Api 'GET' "$BaseUrl/api/notifications/records?bookingNo=$bookingNo&eventType=BOOKING_APPROVED&limit=20" $headers } `
    { param($r) $r.data.Count -ge 1 }
  $notify | ConvertTo-Json -Depth 12

  Write-Step 'Checking audit log for NOTIFY_SENT...'
  $audits = Wait-Until 'audit log' `
    { Invoke-Api 'GET' "$BaseUrl/api/notifications/audits?bookingNo=$bookingNo&action=NOTIFY_SENT&limit=20" $headers } `
    { param($r) $r.data.Count -ge 1 }
  $audits | ConvertTo-Json -Depth 12

  Write-Step 'Checking idempotent record...'
  $idem = Invoke-Api 'GET' "$BaseUrl/api/notifications/idempotent?messageKey=$messageKey&limit=20" $headers
  $idem | ConvertTo-Json -Depth 12
  if ($idem.data.Count -lt 1) { throw 'idempotent record missing.' }

  Write-Step 'Republishing the same outbox payload to verify idempotent duplicate skipping...'
  $republish = Invoke-Api 'POST' "$BaseUrl/api/bookings/outbox/$outboxId/republish" $headers
  $republish | ConvertTo-Json -Depth 8

  $dupAudit = Wait-Until 'duplicate skipped audit' `
    { Invoke-Api 'GET' "$BaseUrl/api/notifications/audits?messageKey=$messageKey&action=DUPLICATE_SKIPPED&limit=20" $headers } `
    { param($r) $r.data.Count -ge 1 }
  $dupAudit | ConvertTo-Json -Depth 12

  Write-Step 'Cancelling booking. This should create and dispatch a BOOKING_CANCELLED event.'
  $cancelBody = @{ operatorUserId = 1; operatorName = 'admin'; cancelReason = 'phase06 smoke test finished' }
  $cancelled = Invoke-Api 'POST' "$BaseUrl/api/bookings/$bookingId/cancel" $headers $cancelBody
  $cancelled | ConvertTo-Json -Depth 12

  $cancelOutbox = Wait-Until 'cancelled outbox message' `
    { Invoke-Api 'GET' "$BaseUrl/api/bookings/outbox?aggregateId=$bookingId&eventType=BOOKING_CANCELLED&limit=20" $headers } `
    { param($r) $r.data.Count -ge 1 }
  $cancelOutbox | ConvertTo-Json -Depth 12

  $dispatch2 = Invoke-Api 'POST' "$BaseUrl/api/bookings/outbox/dispatch?limit=20" $headers
  $dispatch2 | ConvertTo-Json -Depth 8

  $cancelNotify = Wait-Until 'cancel notify record' `
    { Invoke-Api 'GET' "$BaseUrl/api/notifications/records?bookingNo=$bookingNo&eventType=BOOKING_CANCELLED&limit=20" $headers } `
    { param($r) $r.data.Count -ge 1 }
  $cancelNotify | ConvertTo-Json -Depth 12

  Write-Host "`n[Phase06] OK" -ForegroundColor Green
  Write-Host '[Phase06] Completed successfully.' -ForegroundColor Green
} catch {
  Write-Host "`n[Phase06] FAILED" -ForegroundColor Red
  Write-Host $_.Exception.Message -ForegroundColor Red
  if ($_.Exception.Response) {
    Write-Host $_.Exception.Response -ForegroundColor Red
  }
  exit 1
}
